version: '3.5'
services:
  db:
    image: mongo:3.4.10
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data
  
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
  #   container_name: elasticsearch
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms1536m -Xmx1536m"
  #     # - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
  #     # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - xpack.security.enabled=false
  #     - xpack.monitoring.enabled=false
  #     - indices.memory.index_buffer_size=512mb
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #     nproc:
  #       soft: 65535555
  #       hard: 65535555
  #   # # mem_limit: 1792M
  #   # # mem_limit: 1536M
  #   # mem_limit: 1g
  #   cap_add:
  #     - IPC_LOCK
  #   volumes:
  #     - esdata1:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #   networks:
  #     - esnet
  # elasticsearch2:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
  #   container_name: elasticsearch2
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms1536m -Xmx1536m"
  #     # - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
  #     # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.zen.ping.unicast.hosts=elasticsearch"
  #     - xpack.security.enabled=false
  #     - xpack.monitoring.enabled=false
  #     - indices.memory.index_buffer_size=512mb
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #     nproc:
  #       soft: 65535555
  #       hard: 65535555
  #   # # mem_limit: 1792M
  #   # # mem_limit: 1536M
  #   # mem_limit: 1g
  #   cap_add:
  #     - IPC_LOCK
  #   volumes:
  #     - esdata2:/usr/share/elasticsearch/data
  #   networks:
  #     - esnet
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:6.2.1
  #   # image: docker.klickly.com/elk/kibana-optimized:5.3.2
  #   # build:
  #   #   context: .
  #   #   dockerfile: Dockerfile.kibana-optimized
  #   environment:
  #     SERVER_HOST: "0.0.0.0"
  #     # XPACK_SECURITY_ENABLED: "false"
  #     # XPACK_MONITORING_ENABLED: "false"
  #     ELASTICSEARCH_URL: http://elasticsearch:9200
  #     ELASTICSEARCH_STARTUPTIMEOUT: 6000
  #     ELASTICSEARCH_USERNAME: elastic
  #     ELASTICSEARCH_PASSWORD: changeme
  #   volumes:
  #     - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  #   # mem_limit: 1g
  #   ports:
  #     - 5601:5601
  #   networks: 
  #     - esnet
  #   depends_on:
  #     - elasticsearch

volumes:
  mongodb-data:
    driver: local
  # esdata1:
  #   driver: local
  # esdata2:
  #   driver: local

# networks:
#   esnet:
